"use client";
import "./globals.css";
import { QueryClientProvider, QueryClient } from "react-query";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const client = new QueryClient();
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryClientProvider client={client}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </QueryClientProvider>
  );
}
