export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <nav className="bg-gray-800 py-4">
        <div className="container mx-auto flex justify-between items-center">
          <div>
            <a href="/" className="text-white text-xl font-bold">
              My Todo App
            </a>
          </div>
          <ul className="flex space-x-4">
            <li>
              <a href="/dashboard" className="text-white hover:text-gray-300">
                Home
              </a>
            </li>
            <li>
              <a href="/dashboard/list" className="text-white hover:text-gray-300">
                Todos
              </a>
            </li>
            <li>
              <a href="/" className="text-white hover:text-gray-300">
                Logout
              </a>
            </li>
          </ul>
        </div>
      </nav>
      <div>{children}</div>
    </div>
  );
}
